- name: MariaDB installation
  hosts: mariadbs
  become: yes
  tasks:
    - name: Add MariaDB APT repository
      apt_repository:
        repo: 'deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.globo.tech/repo/10.6/ubuntu $(lsb_release -cs) main'
        state: present
        filename: 'mariadb'

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: latest
        update_cache: yes

    - name: Start MariaDB service
      systemd:
        name: mariadb
        state: started

    - name: Verify installation
      ansible.builtin.command: mysql --version
      register: mysql_version

    - debug: var=mysql_version.stdout_lines
