- name: MariaDB installation
  hosts: mariadbs
  become: yes
  tasks:
    - name: Add MariaDB APT repository
      apt_repository:
        repo: 'deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.globo.tech/repo/10.6/ubuntu {{ ansible_distribution_release }} main'
        state: present
        filename: 'mariadb'

    - name: Add MariaDB GPG key
      apt_key:
        url: 'https://mariadb.org/mariadb_release_signing_key.asc'
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: latest

    - name: Start MariaDB service
      systemd:
        name: mariadb
        state: started

    - name: Verify installation
      ansible.builtin.command: mysql --version
      register: mysql_version

    - debug: var=mysql_version.stdout_lines
